---
services:
  dump:
    image: futureys/dump-mysql
    environment:
      LOGIN_USER: root
      LOGIN_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      ANSIBLE_VERBOSITY: 3
      ANSIBLE_FORCE_COLOR: 'True'
    volumes:
      - ./backup/initdb.d:/root/storage
  backup-uploads:
    command:
      - sh
      - -c
      - >-
        apk --update add tzdata
        && cp /usr/share/zoneinfo/Asia/Tokyo /etc/localtime
        && chmod +x /root/storage/backup-uploads.sh
        && /root/storage/backup-uploads.sh
    image: alpine
    volumes:
      - uploads:/var/www/html/web/app/uploads
      - ./backup/inituploads.d:/root/storage
