---
services:
  ssl_certificate:
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
    image: futureys/ssl-certificate:2.0.2
    volumes:
      - pki:/etc/pki

  database:
    command:
      - --ssl-ca=/etc/pki/CA/cacert-${DOMAIN_NAME}.pem
      - --ssl-cert=/etc/pki/tls/certs/servercert-${DOMAIN_NAME}.pem
      - --ssl-key=/etc/pki/tls/private/serverkey-${DOMAIN_NAME}.pem
    depends_on:
      - ssl_certificate
    entrypoint: setup-certificate.sh
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: service
      MYSQL_USER: app
      MYSQL_PASSWORD: ${DATABASE_USER_PASSWORD}
    image: mysql:8.3.0
    ports:
      - target: 3306
        published: 3306
    restart: always
    volumes:
      # To enable SSL for MySQL serving.
      - pki:/etc/pki
      # To wait for creating certificate and setup it.
      - ./database_entrypoint/setup-certificate.sh:/usr/local/bin/setup-certificate.sh
      # To restore database.
      - ./backup/initdb.d:/docker-entrypoint-initdb.d
      # To configure MySQL.
      - ./mysql_conf.d:/etc/mysql/conf.d

  wordpress-fpm:
    build:
      context: wordpress-fpm
    depends_on:
      - database
      - ssl_certificate
    environment:
      # entrypoint
      DOMAIN_NAME: ${DOMAIN_NAME}
      # Bedrock
      DB_NAME: service
      DB_USER: app
      DB_PASSWORD: ${DATABASE_USER_PASSWORD}
      # Optional variables
      DB_HOST: database
      DB_PORT: 3306
      # DB_PREFIX=wp_
      WP_ENV: ${WORDPRESS_ENV?err}
      WP_HOME: https://local.${DOMAIN_NAME}
      WP_SITEURL: https://local.${DOMAIN_NAME}/wp
      # Generate your keys here: https://roots.io/salts.html
      AUTH_KEY: ${WORDPRESS_AUTH_KEY}
      SECURE_AUTH_KEY: ${WORDPRESS_SECURE_AUTH_KEY}
      LOGGED_IN_KEY: ${WORDPRESS_LOGGED_IN_KEY}
      NONCE_KEY: ${WORDPRESS_NONCE_KEY}
      AUTH_SALT: ${WORDPRESS_AUTH_SALT}
      SECURE_AUTH_SALT: ${WORDPRESS_SECURE_AUTH_SALT}
      LOGGED_IN_SALT: ${WORDPRESS_LOGGED_IN_SALT}
      NONCE_SALT: ${WORDPRESS_NONCE_SALT}
      # WordPress
      MYSQL_SSL_CA: /etc/pki/CA/cacert-${DOMAIN_NAME}.pem
      # StaticPress2019-S3
      # @see https://www.php.net/manual/en/function.finfo-open.php
      MAGIC: /etc/httpd/conf/magic
    image: futureys/wordpress-fpm:latest
    volumes:
      # To enable SSL for access to MySQL.
      - pki:/etc/pki
      # To use latest version of project files.
      - ./wordpress-fpm/config:/var/www/html/config
      - ./wordpress-fpm/wp-cli.yml:/var/www/html/wp-cli.yml
      - ./wordpress-fpm/composer.json:/var/www/html/composer.json
      - ./wordpress-fpm/composer.lock:/var/www/html/composer.lock
      - ./wordpress-fpm/web/index.php:/var/www/html/web/index.php
      - ./wordpress-fpm/web/wp-config.php:/var/www/html/web/wp-config.php
      - ./wordpress-fpm/web/app/mu-plugins/bedrock-autoloader.php:/var/www/html/web/app/mu-plugins/bedrock-autoloader.php
      - ./wordpress-fpm/web/app/mu-plugins/disallow-indexing.php:/var/www/html/web/app/mu-plugins/disallow-indexing.php
      - ./wordpress-fpm/web/app/mu-plugins/register-theme-directory.php:/var/www/html/web/app/mu-plugins/register-theme-directory.php
      - ./wordpress-fpm/web/app/mu-plugins:/var/www/html/web/app/mu-plugins
      - ./wordpress-fpm/web/app/plugins/staticpress2019-s3:/var/www/html/web/app/plugins/staticpress2019-s3
      - ./wordpress-fpm/web/app/themes:/var/www/html/web/app/themes
      # See comment at volumes.
      - plugins:/var/www/html/web/app/plugins
      - upgrade:/var/www/html/web/app/upgrade
      - uploads:/var/www/html/web/app/uploads
      - wordpress:/var/www/html/web/wp
      # To restore uploads.
      - ./backup/inituploads.d:/docker-entrypoint-inituploads.d
      # To get static dump
      - ./wordpress-fpm/web/static:/var/www/html/web/static
      # For testing StaticPress2019
      # - ../../projects/wordpress/plugins/staticpress2019:/var/www/html/web/app/plugins/staticpress2019

  web:
    depends_on:
      - wordpress-fpm
      - ssl_certificate
    image: nginx:1.25.5
    # For rebuild static site by StaticPress2019
    # @see https://stackoverflow.com/questions/29924843/how-do-i-set-hostname-in-docker-compose/47264089#47264089
    networks:
      default:
        aliases:
          - local.${DOMAIN_NAME}
    ports:
      - target: 80
        published: 80
      - target: 443
        published: 443
    restart: always
    volumes:
      # To enable SSL for HTTPS serving.
      - pki:/etc/pki
      # Requires to work with nginx.conf.
      - ./wordpress-fpm/web/index.php:/var/www/html/web/index.php
      - ./wordpress-fpm/web/wp-config.php:/var/www/html/web/wp-config.php
      - ./wordpress-fpm/web/app/plugins/staticpress2019-s3:/var/www/html/web/app/plugins/staticpress2019-s3
      - ./wordpress-fpm/web/app/themes:/var/www/html/web/app/themes
      # See comment at volumes.
      - plugins:/var/www/html/web/app/plugins
      - upgrade:/var/www/html/web/app/upgrade
      - uploads:/var/www/html/web/app/uploads
      - wordpress:/var/www/html/web/wp
      # To configure Nginx.
      - ./nginx_conf.d:/etc/nginx/conf.d

# Some directory includes both PHP and static files,
# it requires to share these directories with web service and fpm service.
volumes:
  pki:
  plugins:
  upgrade:
  uploads:
  wordpress:
