---
version: '3.7'
services:
  ssl_certificate:
    container_name: ssl_certificate
    environment:
      DOMAIN_NAME: futureys.net
      USE_MYSQL: 'true'
    image: futureys/ssl-certificate:latest
    volumes:
      - pki:/etc/pki

  database:
    container_name: database
    depends_on:
      - ssl_certificate
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: service
      MYSQL_USER: app
      MYSQL_PASSWORD: ${DATABASE_USER_PASSWORD}
    image: mysql:8
    ports:
      - target: 3306
        published: 3306
    restart: always
    volumes:
      - pki:/etc/pki
      - ./mysql_conf.d:/etc/mysql/conf.d
      - ./initdb.d:/docker-entrypoint-initdb.d

  web:
    container_name: web
    depends_on:
      - ssl_certificate
      - database
    entrypoint:
      - sh
      - -cl
      - "cd /root && ansible-playbook ansistrano-wordpress/deploy_without_ansistrano.yml -i ansistrano-wordpress/inventories/development -vvv --extra-vars '{\"is_container\": true}' && cd /app && heroku local -p 80"
#      - /bin/bash
    environment:
      DB_NAME: service
      DB_USER: app
      DB_PASSWORD: ${DATABASE_USER_PASSWORD}
      # Optional variables
      DB_HOST: database
      MYSQL_SSL_CA: /etc/pki/CA/cacert-futureys.net.pem
      # DB_PREFIX=wp_
      WP_ENV: ${WORDPRESS_ENV?err}
      WP_HOME: http://localhost
      WP_SITEURL: http://localhost/wp
      # @see https://www.php.net/manual/en/function.finfo-open.php
      MAGIC: /etc/httpd/conf/magic
      # Generate your keys here: https://roots.io/salts.html
      AUTH_KEY: ${WORDPRESS_AUTH_KEY}
      SECURE_AUTH_KEY: ${WORDPRESS_SECURE_AUTH_KEY}
      LOGGED_IN_KEY: ${WORDPRESS_LOGGED_IN_KEY}
      NONCE_KEY: ${WORDPRESS_NONCE_KEY}
      AUTH_SALT: ${WORDPRESS_AUTH_SALT}
      SECURE_AUTH_SALT: ${WORDPRESS_SECURE_AUTH_SALT}
      LOGGED_IN_SALT: ${WORDPRESS_LOGGED_IN_SALT}
      NONCE_SALT: ${WORDPRESS_NONCE_SALT}
    image: futureys/heroku-php-apache2:201911.01
    ports:
      - 80:80
    privileged: true
    tty: true
    volumes:
      - pki:/etc/pki
      - ./ansistrano-wordpress:/root/ansistrano-wordpress
      - ./wordpress-s3:/app
      - vendor:/app/vendor
      # - ../plugins:/plugins
volumes:
  pki:
    driver_opts:
      type: tmpfs
      device: tmpfs
  vendor:
