---
version: '3.8'
services:
  ssl_certificate:
    container_name: ssl_certificate
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
      USE_MYSQL: 'true'
    image: futureys/ssl-certificate:latest
    volumes:
      - pki:/etc/pki

  database:
    container_name: database
    depends_on:
      - ssl_certificate
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: service
      MYSQL_USER: app
      MYSQL_PASSWORD: ${DATABASE_USER_PASSWORD}
    image: mysql:8
    ports:
      - target: 3306
        published: 3306
    restart: always
    volumes:
      - pki:/etc/pki
      - ./mysql_conf.d:/etc/mysql/conf.d
      - ./initdb.d:/docker-entrypoint-initdb.d

  fpm:
    # build:
    #   context: fpm
    container_name: fpm
    # Original: CMD ["php-fpm"]
    # @see https://github.com/docker-library/php/blob/b4aeb948e2e240c732d78890ff03285b16e8edda/7.0/fpm/Dockerfile
    command:
      - sh
      - -c
      - >-
        composer ${COMPOSER_COMMAND:-update} --prefer-dist --optimize-autoloader
        && cp -p /etc/pki/CA/cacert-futureys.net.pem /usr/share/ca-certificates/cacert-futureys.net.crt
        && echo cacert-futureys.net.crt >> /etc/ca-certificates.conf
        && update-ca-certificates
        && php-fpm
    depends_on:
      - database
      - ssl_certificate
    environment:
      # Bedrock
      DB_NAME: service
      DB_USER: app
      DB_PASSWORD: ${DATABASE_USER_PASSWORD}
      # Optional variables
      DB_HOST: database
      # DB_PREFIX=wp_
      WP_ENV: ${WORDPRESS_ENV?err}
      WP_HOME: https://local.${DOMAIN_NAME}
      WP_SITEURL: https://local.${DOMAIN_NAME}/wp
      # Generate your keys here: https://roots.io/salts.html
      AUTH_KEY: ${WORDPRESS_AUTH_KEY}
      SECURE_AUTH_KEY: ${WORDPRESS_SECURE_AUTH_KEY}
      LOGGED_IN_KEY: ${WORDPRESS_LOGGED_IN_KEY}
      NONCE_KEY: ${WORDPRESS_NONCE_KEY}
      AUTH_SALT: ${WORDPRESS_AUTH_SALT}
      SECURE_AUTH_SALT: ${WORDPRESS_SECURE_AUTH_SALT}
      LOGGED_IN_SALT: ${WORDPRESS_LOGGED_IN_SALT}
      NONCE_SALT: ${WORDPRESS_NONCE_SALT}
      # WordPress
      MYSQL_SSL_CA: /etc/pki/CA/cacert-${DOMAIN_NAME}.pem
      # StaticPress2019-S3
      # @see https://www.php.net/manual/en/function.finfo-open.php
      MAGIC: /etc/httpd/conf/magic
    # Digest of chialab/php:7.4-fpm
    image: chialab/php@sha256:793ef5d0f9e1e85acbb51507d7d6b97e7df6e7a105d0458801cc2d5711b3b2c8
    volumes:
      - pki:/etc/pki
      - ./wordpress-s3:/app
      - vendor:/app/vendor
    working_dir: /app
    
  web:
    depends_on:
      - fpm
      - ssl_certificate
    container_name: web
    image: nginx:1.19.0
    # For rebuild static site by StaticPress2019
    # @see https://stackoverflow.com/questions/29924843/how-do-i-set-hostname-in-docker-compose/47264089#47264089
    networks:
      default:
        aliases:
          - local.${DOMAIN_NAME}
    ports:
      - target: 80
        published: 80
      - target: 443
        published: 443
    restart: always
    volumes:
      - pki:/etc/pki
      - ./wordpress-s3:/app
      - ./nginx_conf.d:/etc/nginx/conf.d/

volumes:
  pki:
  vendor:
