---
version: '3.2'
services:
  database:
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: service
      MYSQL_USER: app
      MYSQL_PASSWORD: ${DATABASE_USER_PASSWORD}
    image: mysql:5.6
    ports:
      - target: 3306
        published: 3306
    restart: always
    volumes:
      - /opt/datastore/mysql:/var/lib/mysql
      - ./mysql_conf.d:/etc/mysql/conf.d
      - /etc/pki:/etc/pki
      - ./initdb.d:/docker-entrypoint-initdb.d

  cache:
    container_name: redis
    image: redis:4
    ports:
      - target: 6379
        published: 6379
    restart: always

  web:
    container_name: web
    entrypoint:
      - sh
      - -cl
      - "cd /root && ansible-playbook ansistrano-wordpress/deploy_without_ansistrano.yml -i ansistrano-wordpress/inventories/development -vvv --extra-vars '{\"is_container\": true}' && cd /app && heroku local -p 80"
#      - /bin/bash
    environment:
      DB_NAME: service
      DB_USER: app
      DB_PASSWORD: ${DATABASE_USER_PASSWORD}
      # Optional variables
      DB_HOST: database
      # DB_PREFIX=wp_
      WP_ENV: ${WORDPRESS_ENV?err}
      WP_HOME: http://localhost
      WP_SITEURL: http://localhost/wp
      WP_STATIC_PRESS_S3_MAGIC_FILE_PATH: /etc/httpd/conf/magic
      # Generate your keys here: https://roots.io/salts.html
      AUTH_KEY: ${WORDPRESS_AUTH_KEY}
      SECURE_AUTH_KEY: ${WORDPRESS_SECURE_AUTH_KEY}
      LOGGED_IN_KEY: ${WORDPRESS_LOGGED_IN_KEY}
      NONCE_KEY: ${WORDPRESS_NONCE_KEY}
      AUTH_SALT: ${WORDPRESS_AUTH_SALT}
      SECURE_AUTH_SALT: ${WORDPRESS_SECURE_AUTH_SALT}
      LOGGED_IN_SALT: ${WORDPRESS_LOGGED_IN_SALT}
      NONCE_SALT: ${WORDPRESS_NONCE_SALT}
#      SYMFONY_MYSQL_CA: ${SYMFONY_MYSQL_CA}
#      SYMFONY_LOG_LEVEL: ${SYMFONY_LOG_LEVEL}
#      SYMFONY_REDIS_DSN_DEFAULT: redis://cache/0
#      SYMFONY_REDIS_DSN_CACHE: redis://cache/1
#      SYMFONY_REDIS_DSN_SESSION: redis://cache/2
#      SYMFONY_REDIS_DSN_STORAGE: redis://cache/3
    image: futureys/heroku-php-apache2
    links:
      - database
      - cache
    ports:
      - 80:80
    privileged: true
    # restart: always
    tty: true
    volumes:
#      - /etc/pki:/etc/pki
      - ./ansistrano-wordpress:/root/ansistrano-wordpress
      - ./wordpress-s3:/app
#      - /tmp/wordpress/var/cache:/app/var/cache
#      - /tmp/wordpress/var/logs:/app/var/logs
#      - /tmp/wordpress/var/sessions:/app/var/sessions
      - /tmp/wordpress/vendor:/app/vendor
      - /tmp/wordpress/static:/app/web/wp/static
